Require pyglet v1.5.7
When I installed using pyglet 1.4.1 I got the following error when launching main.py (but installing pyglet 1.5.7 resolved the issue):

Unexpected error loading library avutil-56: Could not find module 'avutil-56' (or one of its dependencies). Try using the full path with constructor syntax.
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from gui import Gui
  File "C:\Users\3dpav\3dpav-desktop\gui.py", line 10, in <module>
    from pyglet.media import Player, load
  File "C:\Users\3dpav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyglet\media\__init__.py", line 146, in <module>
    add_default_media_codecs()
  File "C:\Users\3dpav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyglet\media\codecs\__init__.py", line 164, in add_default_media_codecs
    if have_ffmpeg():
  File "C:\Users\3dpav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyglet\media\codecs\__init__.py", line 180, in have_ffmpeg
    from . import ffmpeg_lib
  File "C:\Users\3dpav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyglet\media\codecs\ffmpeg_lib\__init__.py", line 36, in <module>
    from .libavcodec import *
  File "C:\Users\3dpav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyglet\media\codecs\ffmpeg_lib\libavcodec.py", line 45, in <module>
    from . import libavutil
  File "C:\Users\3dpav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyglet\media\codecs\ffmpeg_lib\libavutil.py", line 46, in <module>
    avutil = pyglet.lib.load_library(
  File "C:\Users\3dpav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyglet\lib.py", line 148, in load_library
    lib = ctypes.cdll.LoadLibrary(name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'avutil-56' (or one of its dependencies). Try using the full path with constructor syntax.
Unexpected error loading library avutil-56: Could not find module 'avutil-56' (or one of its dependencies). Try using the full path with constructor syntax.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\3dpav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyglet\media\__init__.py", line 146, in <module>
    add_default_media_codecs()
  File "C:\Users\3dpav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyglet\media\codecs\__init__.py", line 164, in add_default_media_codecs
    if have_ffmpeg():
  File "C:\Users\3dpav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyglet\media\codecs\__init__.py", line 180, in have_ffmpeg
    from . import ffmpeg_lib
  File "C:\Users\3dpav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyglet\media\codecs\ffmpeg_lib\__init__.py", line 36, in <module>
    from .libavcodec import *
  File "C:\Users\3dpav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyglet\media\codecs\ffmpeg_lib\libavcodec.py", line 45, in <module>
    from . import libavutil
  File "C:\Users\3dpav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyglet\media\codecs\ffmpeg_lib\libavutil.py", line 46, in <module>
    avutil = pyglet.lib.load_library(
  File "C:\Users\3dpav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyglet\lib.py", line 148, in load_library
    lib = ctypes.cdll.LoadLibrary(name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'avutil-56' (or one of its dependencies). Try using the full path with constructor syntax.